CRUD/urls.py
from CRUD import views
from django.urls import path

urlpatterns = [
    path('',views.employee_list,name="employee_list"),
    path('add',views.add,name="addnew_employee"),
    path('edit/<int:id>',views.edit,name="edit_employee"),
    path('update/<int:id>',views.update,name="update_employee"),
    path('delete/<int:id>',views.delete,name="delete_employee"),
    path('get',views.get,name="get"),
]

Employee/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CRUD.urls')),
]

CRUD/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Employee(models.Model):
    username=models.CharField(max_length=50,default="")
    firstname=models.CharField(max_length=50,default="")
    lastname=models.CharField(max_length=50,default="")
    email=models.CharField(max_length=50,default="")
    created=models.DateTimeField(blank=True,default=datetime.now())

    def __str__(self):
        return self.username
    

CRUD/forms.py
from django import forms
from django.db.models import fields
from .models import Employee

class EmployeeForm(forms.ModelForm):

    class Meta:
        model=Employee
        fields='__all__'
        widgets={'username':forms.TextInput(attrs={'class':'form-control'}),
                    'firstname':forms.TextInput(attrs={'class':'form-control'}),
                    'lastname':forms.TextInput(attrs={'class':'form-control'}),
                    'email':forms.TextInput(attrs={'class':'form-control'}),
        }

CRUD/views.py
from django.db.models import query
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from CRUD.forms import EmployeeForm
from .forms import EmployeeForm
from datetime import datetime

from CRUD.models import Employee

# Create your views here.
def employee_list(request):
    employees=Employee.objects.all()
    return render(request,'employee_list.html',{'employees':employees})

def add(request):
    if request.method=="POST":
        username=request.POST['username']
        firstname=request.POST['firstname']
        lastname=request.POST['lastname']
        email=request.POST['email']
        add=Employee(username=username,firstname=firstname,lastname=lastname,email=email,created=datetime.today())
        add.save()

    latest_by=[Employee.objects.latest('created')]
    param={'latest_by':latest_by}
    return render(request,'add.html',param)

def edit(request,id):
    employee=Employee.objects.filter(id=id)
    return render(request,'edit.html',{'employee':employee})

def update(request,id):
    employee=Employee.objects.get(id=id)
    form = EmployeeForm(request.POST or None,instance = employee)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form})

def delete(request,id):
    employee=Employee.objects.get(id=id)
    employee.delete()
    return redirect("/")

def get(request):
    query=request.GET['query']
    param=Employee.objects.filter(id=query)
    context={'param':param}
    return render(request,"get.html",context)

templates/add.html
{% extends 'base.html' %}
{% block content %}
<h3 class="text-center bg-success">User Added Currently</h3>
<table id="bootstrapdatatable" class="text-white bg-success mb-3 table-resposive">
  <thead>
    <tr>
      <th scope="col"><input type="checkbox" id="checkall" /></th>
      <th scope="col">ID</th>
      <th scope="col">Username</th>
      <th scope="col">Firstname</th>
      <th scope="col">Lastname</th>
      <th scope="col">Email</th>
      <th scope="col">Created</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in latest_by %}
    <tr class="text-white bg-dark">
      <td><input type="checkbox" class="checkthis" /></td>
      <td>{{employee.id}}</td>
      <td>{{employee.username}}</td>
      <td>{{employee.firstname}}</td>
      <td>{{employee.lastname}}</td>
      <td>{{employee.email}}</td>
      <td>{{employee.created}}</td>
      </tr>
{% endfor %}
      </tbody>
      </table>
<div class="container">
<a href="/" class="btn btn-secondary">Back</a>
</div>

{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" charset="utf8"
        src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

    <title>Hello, world!</title>
</head>

<body>
    <div class="container-fluid mt-3 mb-0 list_employee">
        <div class="card text-white bg-dark">
            <h1 class="card-header">Employee Register</h1>
            <div class="card-body">
                <h5 class="card-title small"> Python Django Project for implementing CRUD operations</h5>
            </div>
        </div>
        <h4 class='text-center text-white bg-dark mt-0'>I'll show the list of employee from the table</h4>
        <p class="card-text">{% block content %}{% endblock content %}</p>
    </div>
    <script>
        $(document).ready(function () {
            $('#bootstrapdatatable').DataTable({
                "aLengthMenu": [[7,10,25,-1],[7,10,25,"All"]],
                
            })
        });
    </script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


</body>

</html>

templates/edit.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">Update Employee details</h1>
<div class="container">
{% for employee in employee %}
<form method="POST" class="post-form" action='/update/{{employee.id}}'>
{% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Employee ID</label>
    <input type="text" class="form-control" name="id" id="id_id" value={{employee.id}}>
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Username</label>
    <input type="text" class="form-control" name="username" id="id_username" value={{employee.username}}>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Firstname</label>
    <input type="text" class="form-control" name="firstname" id="id_firstname" value={{employee.firstname}}>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Lastname</label>
    <input type="text" class="form-control" name="lastname" id="id_lastname" value={{employee.lastname}}>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Email</label>
    <input type="text" class="form-control" name="email" id="id_email" value={{employee.email}}>
  </div>
  <button type="submit" class="btn btn-primary">Update</button>
  <a href="/" class="btn btn-light mx-2">Back</a>
</form>
{% endfor %}
</div>
{% endblock content %}

templates/employee_list.html
{% extends 'base.html' %}
{% block content %}


<table id="bootstrapdatatable" class="text-white bg-success mb-3 table-resposive">
  <thead>
    <tr>
      <th scope="col"><input type="checkbox" id="checkall" /></th>
      <th scope="col">ID</th>
      <th scope="col">Username</th>
      <th scope="col">Firstname</th>
      <th scope="col">Lastname</th>
      <th scope="col">Email</th>
      <th scope="col">Created</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employees reversed %}
    <tr class="text-white bg-dark">
      <td><input type="checkbox" class="checkthis" /></td>
      <td>{{employee.id}}</td>
      <td>{{employee.username}}</td>
      <td>{{employee.firstname}}</td>
      <td>{{employee.lastname}}</td>
      <td>{{employee.email}}</td>
      <td>{{employee.created}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div class="container">
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#getModal">
    Get Employee Detail
  </button>
  <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#addModal">Add New
    Employee</button>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#getModal">
    Update Employee
    </button>

  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#getModal">Delete</button>



  <!-- GET Modal -->
  <div class="modal fade" id="getModal" tabindex="-1" aria-labelledby="getModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="getModalLabel">Enter Your's ID</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="/get" action="get">
            {% csrf_token %}
            <div class="mb-3">
              <input type="search" class="form-control" name="query" id="query" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text">We'll never share your id with anyone else.</div>
            </div>
        </div>
        <div class="modal-footer">
          <a href="/get"> <button type="submit" class="btn btn-primary">Submit</button> </a>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Add Modal -->
  <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addModalLabel">Add New Employee</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="/add" method="POST">
            {% csrf_token %}
            <input type="text" class="form-control" name="username" id="username" placeholder="Username"><br>
            <input type="text" class="form-control" name="firstname" id="firstname" placeholder="Firstname"><br>
            <input type="text" class="form-control" name="lastname" id="lastname" placeholder="Lastname"><br>
            <input type="text" class="form-control" name="email" id="email" placeholder="Email"><br>
            <div class="modal-footer">
              <button type="submit" class="btn btn-primary my-1" onclick=Add()>Submit</button>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </form>
        </div>
        <script>
          function Add() {
            location.replace("http://127.0.0.1:8000/add")
          }
        </script>
      </div>
    </div>
  </div>



  <!-- Delete Modal -->
  <div class="modal fade" id="getModal" tabindex="-1" aria-labelledby="getModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Enter Your's ID</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="/get" action="get">
            {% csrf_token %}
            <div class="mb-3">
              <input type="search" class="form-control" name="query" id="query" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text">We'll never share your id with anyone else.</div>
            </div>
        </div>
        <div class="modal-footer">
          <a href="/get"> <button type="submit" class="btn btn-primary">Submit</button> </a>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock content %}

templates/get.html
{% extends 'base.html' %}
{% block content %}
<h1 class="bg-warning text-center">RESPONSE DATA</h1>
<table id="bootstrapdatatable" class="text-dark bg-success mb-3 table-resposive">
  <thead>
    <tr>
      <th scope="col"><input type="checkbox" id="checkall" /></th>
      <th scope="col">ID</th>
      <th scope="col">Username</th>
      <th scope="col">Firstname</th>
      <th scope="col">Lastname</th>
      <th scope="col">Email</th>
      <th scope="col">Created</th>
    </tr>
  </thead>
  <tbody>
  {% for employee in param %}
    <tr class="text-white bg-dark">
      <td><input type="checkbox" class="checkthis" /></td>
      <td>{{employee.id}}</td>
      <td>{{employee.username}}</td>
      <td>{{employee.firstname}}</td>
      <td>{{employee.lastname}}</td>
      <td>{{employee.email}}</td>
      <td>{{employee.created}}</td>
        <td><a href="/edit/{{employee.id}}" class="btn btn-warning btn-xs">Edit</a></td>
      <td><button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete
  </button></td></tr>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Employee</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <h5>Are You Sure Want To Delete..??</h5>
        </div>
        <div class="modal-footer">
          <a href="/delete/{{employee.id}}" class="btn btn-danger btn-xs">Delete</a>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </form>
        </div>
      </div>
    </div>
  </div>

    </tr>
    {% endfor %}
  </tbody>
</table>
</div class="container">
<a href="/" class="btn btn-secondary">Back</a>
</div>
{% endblock content %}